let peso = Number(prompt("Digite seu peso:"))
let altura = Number(prompt("Digite sua altura: "))
let imc = peso / (altura**2)
let valor_arredondado = parseFloat(imc.toFixed(2))
document.write(`Seu IMC é ${valor_arredondado}`)